// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Natega.Shared.Models;

#nullable disable

namespace Natega.Shared.Migrations
{
    [DbContext(typeof(NategaContext))]
    partial class NategaContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Natega.Shared.Models.Stage_New_Dawly", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("arabic_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("s1")
                        .HasColumnType("int");

                    b.Property<int>("s10")
                        .HasColumnType("int");

                    b.Property<int>("s14")
                        .HasColumnType("int");

                    b.Property<int>("seating_no")
                        .HasColumnType("int");

                    b.Property<int>("student_case")
                        .HasColumnType("int");

                    b.Property<string>("student_case_desc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Stage_New_Dawly");
                });

            modelBuilder.Entity("Natega.Shared.Models.Stage_New_Search", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("arabic_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("c_flage")
                        .HasColumnType("real");

                    b.Property<int>("seating_no")
                        .HasColumnType("int");

                    b.Property<int>("student_case")
                        .HasColumnType("int");

                    b.Property<string>("student_case_desc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("total_degree")
                        .HasColumnType("real");

                    b.HasKey("ID");

                    b.ToTable("Stage_New_Search");
                });

            modelBuilder.Entity("Natega.Shared.Models.X_Search", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("no")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("X_Search");
                });
#pragma warning restore 612, 618
        }
    }
}
